### ISSUE TITLE
Generate miRBase alignment references

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-smRNAseq#15]
The miRBase index paths are currently [set to project-paths](https://github.com/SciLifeLab/NGI-smRNAseq/blob/master/conf/uppmax.config#L261-L318) in the config. This isn't ideal.

* Can we put indexes for these in a more central location?
* Assuming that generating these indices is fast, can we add an indexing step to the pipeline?

**Comment by zhenyisong** [comment]
The prime miRBase does contain the miRNA mature/hairpin sequences. But they are mRNA, I mean, they use U instead of T in the sequences. I have to write something before to index them. They best solution is to add indexing step. The project path did not specify the index name. To use the indexing function in Bowtie, we have to specify the basename of the index. Does the protocol automatically recognize the basename?

**Comment by ewels** [comment]
Ah yes of course. It was a while ago that we generated these, perhaps @chuan-wang can remember how we made them? Looks like [FASTX-Toolkit](http://hannonlab.cshl.edu/fastx_toolkit/commandline.html#fasta_nucleotide_changer_usage) has a command for it.

The config paths include the basename, so for example with GRCh37:
```
 '/proj/b2013064/nobackup/genomes/miRBasev21/bowtie/hairpin/hairpin_GRCh37'
```
..the basename is `hairpin_GRCh37`

**Comment by chuan-wang** [comment]
Yes, I did it with FASTX. First converted to single-line format (`fasta_formatter`), then U to T conversion (`fasta_nucleotide_changer`)

**Comment by ewels** [comment]
Ok great - maybe we can add these steps to the pipeline then.

Looks like the miRBase FASTA files are included in the iGenomes resource too, used by the main alignments (and available on AWS etc). So we can just add links to those in the config and then build the indices dynamically (assuming that it's fast).

eg. in the config:

```groovy
'GRCh37' {
  hairpin = '/sw/data/uppnex/igenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/SmallRNA/hairpin.fa'
  mature  = '/sw/data/uppnex/igenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/SmallRNA/mature.fa'
  bowtie  = '/sw/data/uppnex/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/BowtieIndex/genome'
  bowtie2 = '/sw/data/uppnex/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/Bowtie2Index/genome'
  fasta   = '/sw/data/uppnex/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta'
  gtf     = '/sw/data/uppnex/igenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf'
}
```

**Comment by chuan-wang** [comment]
Fixed in PR https://github.com/SciLifeLab/NGI-smRNAseq/pull/16.
