### ISSUE TITLE
Use bowtie 1 for human genome alignment

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-smRNAseq#3]
Probably shouldn't have put Bowtie 2 into the latest change.

Need to read this paper and take on advice:
http://bib.oxfordjournals.org/content/16/6/950.full

> Alignments performed using Bowtie 2 resulted in an even greater number of miRNAs with higher counts; examination of the alignment output revealed that many of these were attributed to the allowance of insertions and deletions.
> 
> Bowtie 2, which was developed for gapped alignment, was included in our comparison to illustrate the consequences of selecting an inappropriate aligner.

**Comment by zhenyisong** [comment]
There is another paper regarding the same issue, "Evaluation of microRNA alignment techniques". PMID: 27284164. I used BWA, However. But you seemed to miss the step in the instruction of how to index the hairpin/mature miRNA by bowtie. Is there any public script ( or included in your module) to finish the task and reproducible for the future research? Besides, the index name in the default setting is 'genome' from my understanding. This is not  explicitly clarified. Thanks.

**Comment by ewels** [comment]
Hi @zhenyisong,

Currently the pipeline uses [hardcoded paths](https://github.com/SciLifeLab/NGI-smRNAseq/blob/master/conf/uppmax.config#L261-L318) to the pre-built indexes. These work with the `--genome` option. The paths are in a config file, so it should be simple to customise where to find them. However, it would be nice to add indexing steps as you suggest (and as we have done in other similar pipelines). I've created a new issue for this here: #15

Phil

**Comment by ewels** [comment]
ps. instructions for how to make your own indices before then [are here](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#the-bowtie2-build-indexer).

**Comment by ewels** [comment]
Moved to nf-core/smrnaseq
