### ISSUE TITLE
seed length bowtie and multimappers 

### ISSUE THREAD

**Issue by vincent-van-hoef** [SciLifeLab/NGI-smRNAseq#32]
First of all, thanks for this great pipeline! 

I have a question regarding the mapping parameters supplied to bowtie when mapping reads to the mature miRBASE database. If I am not mistaken, by setting the seed length to 15 (as done here by `-l 15`), there are no mismatches allowed in the 15 leftmost nucleotides but mismatches from nucleotide 16 on are allowed and reported as valid hits. In my dataset this seems to result in a substantial number of miRNAs that only differ in the 3'end getting the exact same counts... I'm a novice at miRNA analysis so I was wondering whether there is there a reason for fixing this parameter at 15? Thanks!

**Comment by ewels** [comment]
Hi @vincent-van-hoef,

I'll let @chuan-wang reply to this one as he was the one who looked into the aligner settings to use. I _think_ we used recommended parameters from somewhere, but I'm not totally sure where.

Phil

**Comment by chuan-wang** [comment]
Hi @vincent-van-hoef and @ewels, the bowtie parameters were set by our former colleague @Hammarn. Rickard, do you have any reference for this setting?
Best,
Chuan

**Comment by ewels** [comment]
Personally I hadn't realised that the seed length was anchored to the 5' end of the read. I think that the intention was that we should require a perfect match of at least 15 nucleotides. Perhaps we should adjust these parameters though.

Phil

**Comment by chuan-wang** [comment]
I will do some investigation in publications about this.
/chuan

**Comment by vincent-van-hoef** [comment]
I'm not quite sure what the recommendations are here. Setting seed length to 20 should result in more unique alignments, I think. 

Also, the -n 1 setting as it is now actually allows for one mismatch in the 15nt seed region. Maybe that is also a bit lenient for sequencing miRNAs?

**Comment by chuan-wang** [comment]
Hi, I found two interesting articles about aligners:
1) [https://academic.oup.com/bib/article/16/6/950/226343](https://academic.oup.com/bib/article/16/6/950/226343). This paper tested both `bowtie -n 1 -l 8 -a --best` and `bowtie -n 0 -l 8 -a --best` plus bowtie2, bwa and novoalign. As far as I can see the results were similar.
2) [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4931105](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4931105). This paper tested more parameters of bowtie. But they didn't use seed options (-l or -n) but -k instead. Take-home message is that `bowtie -best -strata -k 1 -m 1` worked well overall.
Best,
Chuan

**Comment by vincent-van-hoef** [comment]
Sorry, the -n 1 setting I mentioned is when mapping against the hairpin miRNA database. For the mature miRNA mapping it is indeed -n 0...

**Comment by chuan-wang** [comment]
Change bowtie parameters to `--best --strata -k 1 -m 1` in PR #33.

**Comment by ewels** [comment]
Ok, parameters updated and merged.

@vincent-van-hoef - if you could pull the latest version and see how the results look now that would be great!

@chuan-wang - we need to make some releases here and add a `CHANGELOG.md`, these kinds of changes are pretty terrible for reproducibility 😉

**Comment by vincent-van-hoef** [comment]
Thanks for a very fast response! @ewels - Will do!

**Comment by vincent-van-hoef** [comment]
Seems to have worked:

Before:
```
     "B-1043166_2_1.mature.count" "B-1043166_7_1.mature.count"
"hsa-let-7a-5p" 24925 2833
"hsa-let-7a-3p" 40 0
"hsa-let-7a-2-3p" 1 0
"hsa-let-7b-5p" 24901 2838
"hsa-let-7b-3p" 86 0
"hsa-let-7c-5p" 24918 2833
```

After:
```
     "B-1043166_2_1.mature.count" "B-1043166_7_1.mature.count"
"hsa-let-7a-5p" 14853 129
"hsa-let-7a-3p" 45 0
"hsa-let-7a-2-3p" 1 0
"hsa-let-7b-5p" 8682 2788
"hsa-let-7b-3p" 95 0
"hsa-let-7c-5p" 2026 68
```

Thanks!

**Comment by ewels** [comment]
Fantastic - thanks for letting us know! Thanks @chuan-wang for the fix.

**Comment by maxulysse** [comment]
@chuan-wang @ewels I started a changelog a couple of months ago for Sarek, definitively great.
Are we advising people to use this for nf-core as well?

**Comment by ewels** [comment]
Yup! `nf-core lint` [checks for it](https://github.com/nf-core/tools/blob/master/nf_core/lint.py#L142) already..

Should probably write some documentation about expected formatting though.
